# Generated by Django 4.2.5 on 2023-10-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tarjeta1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numTelefono", models.CharField(max_length=100)),
                ("numTelefonoEmergencia", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("whatsapp", models.BooleanField()),
                ("numWhatsapp", models.CharField(max_length=100)),
            ],
        ),
    ]
